import {
  AirVent,
  BatteryPlus,
  Bed,
  BedDouble,
  BookCheck,
  BrushCleaning,
  Building2,
  Calendar,
  ChartColumn,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CreditCard,
  DollarSign,
  DoorOpen,
  Eclipse,
  Ellipsis,
  EllipsisVertical,
  Eye,
  EyeOff,
  Funnel,
  GlassWater,
  Heater,
  Hotel,
  HousePlug,
  Key,
  LayoutDashboard,
  Lock,
  LockOpen,
  LogOut,
  Mail, Microwave,
  MonitorCog,
  MonitorSmartphone,
  Palette,
  Percent,
  Phone,
  Refrigerator,
  Search,
  Settings,
  Shield, Shredder,
  SoapDispenserDroplet,
  Toilet,
  TrendingDown,
  TrendingUp,
  TrendingUpDown,
  TriangleAlert, Tv,
  User,
  UserCheck,
  UserRoundCog,
  Users, Waves,
  Wifi,
  Grid2X2,
  DoorClosed,
  Vault,
  Coffee,
  CookingPot,
  Lamp,
  MapPinHouse,
  CircleParking,
  CableCar,
  Shirt,
  ShieldUser,
  AlignHorizontalSpaceBetween,
  Antenna,
  Luggage,
  PawPrint,
  Cigarette,
  Gem,
  Dumbbell,
  Bubbles,
  Hospital,
  Wind,
  Bath,
  Gamepad2,
  Swords,
  LandPlot,
  Space,
  LibraryBig,
  Soup,
  HandPlatter,
  Wine,
  Utensils,
  Caravan,
  CupSoda,
  UtensilsCrossed,
  Landmark,
  Columns4,
  Store,
  Beer,
  Handshake,
  BriefcaseBusiness,
  Presentation,
  Printer,
  Network,
  ScanEye,
  Accessibility,
  BookA,
  Ear,
  CircleStar,
  Car,
  IdCardLanyard,
  Building,
  CirclePlus,
  CarFront,
  BottleWine,
  ConciergeBell,
  Crown,
  Briefcase,
  Dices,
  Plane,
  Watch,
  University,
  Snowflake,
  WalletMinimal,
  Leaf,
  Box,
  Umbrella
} from 'lucide-angular';


export const icons = {
  eye:{
    on: Eye,
    off: EyeOff
  },
  email: Mail,
  phone: Phone,
  user: User,
  password: {
    hidden: Lock,
    visible: LockOpen
  },
  organization: Building2,
  settings: {
    normal: Settings,
    system: MonitorCog,
    profile: UserRoundCog
  },
  sidebar:{
    dashboard: LayoutDashboard,
    users: Users,
    hotels: Building2,
    revenue: DollarSign,
    analytics: ChartColumn,
    card: CreditCard,
    shield: Shield
  },
  arrowDirection:{
    up: ChevronUp,
    down: ChevronDown,
    left: ChevronLeft,
    right: ChevronRight,
  },
  logout:LogOut,
  bed: Bed,
  calender: Calendar,
  percentage: Percent,
  trending:{
    up: TrendingUp,
    down: TrendingDown,
    upDown: TrendingUpDown
  },
  alert:{
    triangle: TriangleAlert
  },
  key:Key,
  userCheck: UserCheck,
  search: Search,
  filter: Funnel,
  ellipsis:{
    horizontal: Ellipsis,
    vertical: EllipsisVertical
  },
  theme: Palette,
  amenityCategory: {
    base: HousePlug,
    categories:{
      Basic:{
        base: BookCheck,
        amenities:{
          'Wi-Fi': Wifi,
          'Air Conditioning': AirVent,
          Heating: Heater,
          'Electricity Backup': BatteryPlus,
          Housekeeping: BrushCleaning,
          Toiletries: SoapDispenserDroplet,
          'Hot Water': Waves,
          'Drinking Water': GlassWater,
          'Linen & Towels': BedDouble,
          'Iron & Board': Shredder
        }
      },
      Room:{
        base: DoorOpen,
        amenities: {
          Television: Tv,
          'Mini Fridge': Refrigerator,
          Microwave: Microwave,
          'Work Desk': MonitorSmartphone,
          Balcony: Grid2X2,
          Wardrobe: DoorClosed,
          Safe: Vault,
          'Coffee Maker': Coffee,
          Kitchenette: CookingPot,
          'Bedside Lamp': Lamp,
        }
      },
      Property:{
        base: MapPinHouse,
        amenities: {
          Parking: CircleParking,
          Elevator: CableCar,
          Laundry: Shirt,
          Security: ShieldUser,
          Reception: User,
          Garden: AlignHorizontalSpaceBetween,
          Terrace: Antenna,
          'Luggage Storage': Luggage,
          'Pet Friendly': PawPrint,
          'Smoking Area': Cigarette
        }
      },
      'Leisure & Wellness':{
        base: Gem,
        amenities:{
          'Swimming Pool': Waves,
          Gym: Dumbbell,
          Apa: Bubbles,
          Sauna: Wind,
          Jacuzzi: Bath,
          'Game Room': Gamepad2,
          Playground: Swords,
          'Sports Court': LandPlot,
          'Yoga Area': Space,
          Library: LibraryBig
        }
      },
      'Food & Beverage':{
        base: HandPlatter,
        amenities:{
          Restaurant: Utensils,
          Bar: Wine,
          Breakfast: Coffee,
          'Room Service': Caravan,
          'Coffee Shop': CupSoda,
          Buffet: UtensilsCrossed,
          'Banquet Hall': Landmark,
          'BBQ Facilities': Columns4,
          'Vending Machines': Store,
          'Mini Bar': Beer,
        }
      },
      'Business & Events':{
        base: Handshake,
        amenities:{
          'Meeting Room': BriefcaseBusiness,
          'Conference Hall': Presentation,
          'Business Center': Printer,
          'Coworking Space': Users,
          'High-speed Internet': Network,
        }
      },
      Accessibility:{
        base: Accessibility,
        amenities:{
          'Wheelchair Access': Accessibility,
          'Accessible Bathroom': Bath,
          'Braille Signage': BookA,
          'Hearing Assistance': Ear,
          'Elevator Access': CableCar
        }
      },
      'Luxury & Premium':{
        base: CircleStar,
        amenities:{
          'Valet Parking': Car,
          'Private Pool': Waves,
          'Butler Service': IdCardLanyard,
          'Rooftop Lounge': Building,
          'Helipad': CirclePlus,
          'Limousine Service': CarFront,
          'Wine Cellar': BottleWine,
          'Personal Concierge': ConciergeBell
        }
      }
    }
  },
  hotelCategory: {
    'Luxury Hotel': Crown,
    'Resort': Umbrella,
    'Boutique Hotel': Gem,
    'Casino Hotel': Dices,
    'Wellness & Spa Hotel': Bubbles,
    'Heritage Hotel': Landmark,
    'Business Hotel': Briefcase,
    'Airport Hotel': Plane,
    'Extended Stay Hotel': Watch,
    'All-Inclusive Hotel': Utensils,
    'Serviced Apartment': Building,
    'Convention Hotel': University,
    'Ski Resort Hotel': Snowflake,
    'Beachfront Hotel': Waves,
    'Budget Hotel': WalletMinimal,
    'Hostel': Users,
    'Motel': Car,
    'Bed & Breakfast (B&B)': Coffee,
    'Capsule Hotel': Box,
    'Eco Hotel': Leaf
  }
}
